development:
      host: localhost
      adapter: mysql2
      database: Codebrahma_app
      port: 3000
      username: root
      password: nimbu

test: &test
      host: localhost
      adapter: mysql2
      database: Codebrahma_app
      port: 3000
      username: root
      password: nimbu

production:
      host: localhost
      adapter: mysql2
      database: Codebrahma_app
      port: 3000
      username: root
      password: nimbu